hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true

---

init-db: true
init-scripts:
  - schema.sql
  - data.sql

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
  profiles: test