hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true

init-db: true
init-scripts:
  - schema.sql
  - data.sql

security:
  saml2:
    metadata-url:

server:
  port: 8443
  ssl:
    enabled: true
    key-alias:
    key-store:
    key-store-password:

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
