api:
  iex:
    url: https://api.iextrading.com/1.0/
    
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: false
  show_sql: true

init-db: true
init-scripts:
  - schema.sql
  - data.sql

security:
  saml2:
    metadata-url:

server:
  port: 8443
  ssl:
    enabled: true
    key-alias:
    key-store:
    key-store-password:

spring:
  datasource:
    url: jdbc:h2:mem:~/esi-dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sysadmin
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
  profiles: dev

---
api:
  iex:
    url: https://api.iextrading.com/1.0/

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: false
  show_sql: true

init-db: true
init-scripts:
  - schema.sql
  - data.sql

spring:
  datasource:
    url: jdbc:h2:mem:~/esi-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sysadmin
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
  profiles: test

---
api:
  iex:
    url: https://api.iextrading.com/1.0/

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: false
  show_sql: true

init-db: true
init-scripts:
  - schema.sql
  - data.sql

spring:
  datasource:
    url: jdbc:h2:mem:~/esi-pro;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sysadmin
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: false
      format-sql: true
    show-sql: true
  profiles: pro